### PR TITLE
Add require parameter for options

### PR DESCRIPTION
**Pull request by mdom**

### CODE REVIEW

**Comment by mlawren** [comment]
Hi Mario, thanks for contributing again.

I'm happy to add a "required" flag to opts, but I'm not sure about it being satisfied by a default value. 

For comparison: the arg "require" attribute indicates that the user MUST provide it, as OptArgs currently raises an error *before* the default gets looked at. I.e. the current behaviour is effectively that a "require" and a "default" conflict, even though I don't check for that. (Should I?)

So my thinking is that an opt "require" should behave the same way. Why would an author make an --option required if they are going to provide a default? Doesn't quite make sense to me. Thoughts?

**Comment by mlawren** [comment]
On a related note I'm thinking up better ways of indicating required arguments and options:

Markup / highlighting:

```
usage: simple AAA [BBB] [OPTIONS...]

  Arguments:
  * AAA                  some kind of arg
    BBB                  other some kind of arg [meh]

  Options:
    --help,         -h   print help message and exit
    --quiet,        -q   work quietly
  * --required=STR, -r   other some kind of arg
```

Rearranging:

```
usage: simple AAA [BBB] [OPTIONS...]

  Required:
    AAA                  some kind of arg
    --required=STR, -r   other some kind of arg

  Optional:
    BBB                  other some kind of arg [meh]
    --help,         -h   print help message and exit
    --quiet,        -q   work quietly
```

Put required options on the usage: line:
```
usage: simple AAA [BBB] --required STR [OPTIONS...]

  Arguments:
    AAA                  some kind of arg
    BBB                  other some kind of arg [meh]

  Options:
    --help,         -h   print help message and exit
    --quiet,        -q   work quietly
    --required=STR, -r   other some kind of arg
```



Thoughts?

**Comment by mdom** [comment]
On Fri, Jan 21, 2022 at 01:46:36AM -0800, Mark Lawrence wrote:
> I'm happy to add a "required" flag to opts, but I'm not sure about it
> being satisfied by a default value.

You are right, that's not the correct behaviour. I just push a new
commit to change that.
 
 Cheers, Mario

**Comment by mlawren** [comment]
Hi Mario,

I've made a bunch of changes that break this pull request, but also probably make it obsolete. There is still plenty of thinking & discussion needed to refine the output.... perhaps you could take a look at the latest 'main' branch and open up a new issue or pr if you have new ideas?

Thanks, Mark

**Comment by mdom** [comment]
On Tue, Jan 25, 2022 at 01:08:44PM -0800, Mark Lawrence wrote:
> I've made a bunch of changes that break this pull request, but also
> probably make it obsolete. There is still plenty of thinking &
> discussion needed to refine the output.... perhaps you could take a
> look at the latest 'main' branch and open up a new issue or pr if you
> have new ideas?

Works like a charm! Thank you! Do you think you could release this
version to cpan or are there any showstoppers?

Cheers, Mario

**Comment by mlawren** [comment]
Still some work planned in (hopefully) the next days:

- more detailed SubCmd usage items
- code cleanups
- Refactor or remove the StatusLine module (not sure it actually belongs in OptArgs2)

But if that takes too long I'll cut a release. I think the testers have not turned up anything dramatic recently.

**Pull request closed without merging**
